-- AlterTable
ALTER TABLE "conversations" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "messages" ALTER COLUMN "submitted_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "completed_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "context_cutoff" SET DATA TYPE TIMESTAMPTZ(6);
